version: '3.8'

services:
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=username
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=my_database
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
      dockerfile: ${DOCKERFILE:-Dockerfile}  # Use DOCKERFILE env if set, else default to Dockerfile
    platform: ${DOCKER_PLATFORM:-linux/amd64}  # Default to amd64, override if needed
    environment:
      - RUST_LOG=info
      - DATABASE_URL=postgres://username:password@db:5432/my_database
      - SQLX_OFFLINE=true
    ports:
      - "3030:3030"
    depends_on:
      - db

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/frontend
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend_test:
    image: "rust:latest"
    working_dir: /project
    volumes:
      - ./:/project
    command: ["cargo", "test", "--manifest-path", "backend/Cargo.toml", "--test", "backend_tests"]

  swagger-ui:
    image: swaggerapi/swagger-ui
    ports:
      - "8080:8080"
    environment:
      - SWAGGER_JSON=/spec/openapi.yaml
    volumes:
      - ./openapi:/spec

volumes:
  db_data:
