version: '3.8'
services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "3030:3030"
    volumes:
      - ./backend:/backend
    environment:
      - RUST_LOG=info

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    volumes:
      - ./frontend:/frontend
    environment:
      - CHOKIDAR_USEPOLLING=true

  backend_test:
    image: "rust:latest"
    working_dir: /project
    volumes:
      - ./:/project
    command: ["cargo", "test", "--manifest-path", "backend/Cargo.toml", "--test", "backend_tests"]
